categorias:
  - nome: Servidores
    servidores:
        - hostname: srvapl1-ma
          descricao: servidor de aplicação
          ip: 172.23.1.1
        - hostname: srvapl1-ma
          descricao: servidor de aplicação
          ip: 172.23.1.1
        - hostname: srvapl1-ma
          descricao: servidor de aplicação
          ip: 172.23.1.1
        - hostname: srvapl1-ma
          descricao: servidor de aplicação
          ip: 172.23.1.1
  - nome: Firewall
    firewall:
        - hostname: fw01
          descricao: servidor de aplicação
          ip: 172.23.1.1
  - nome: Switches
    swithces:
        - hostname: fw01
          descricao: sw01
          ip: 172.23.4.1